service: aws-postgres-server

frameworkVersion: '2'

custom:
  vpc:
    securityGroupIds:
      - sg-36cc262a
    subnetIds:
      - subnet-c30953e2
      - subnet-788fd31e
      - subnet-b2fc9c83
      - subnet-f66d81ba
      - subnet-ac92cbf3
      - subnet-9ac8de94

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'
  iam:
    role: arn:aws:iam::321082332978:role/yoyo-lambda-s3-read-role

plugins:
  - serverless-offline

functions:
  createUser:
    handler: resources/users.createUser
    vpc: ${self:custom.vpc}

  getUser:
    handler: resources/users.getUser
    vpc: ${self:custom.vpc}
    events:
      - http:
          path: /user/{username}
          method: get
          authorizer:
            arn: arn:aws:cognito-idp:us-east-1:321082332978:userpool/us-east-1_mLWq9MaYx

  updateUser:
    handler: resources/users.updateUser
    vpc: ${self:custom.vpc}
    events:
      - http:
          path: /user
          method: put
          authorizer:
            arn: arn:aws:cognito-idp:us-east-1:321082332978:userpool/us-east-1_mLWq9MaYx

  getUserOrders:
    handler: resources/users.getUserOrders
    vpc: ${self:custom.vpc}
    events:
      - http:
          path: /user/orders/{username}/{page}
          method: get
          authorizer:
            arn: arn:aws:cognito-idp:us-east-1:321082332978:userpool/us-east-1_mLWq9MaYx
  
  getUserWalletBalance:
    handler: resources/users.getUserWalletBalance
    vpc: ${self:custom.vpc}
    events:
      - http:
          path: /user/balance/{username}
          method: get
          authorizer:
            arn: arn:aws:cognito-idp:us-east-1:321082332978:userpool/us-east-1_mLWq9MaYx

  getMenu:
    handler: resources/menu.getMenu
    vpc: ${self:custom.vpc}
    events:
      - http:
          path: /menu
          method: post
          authorizer:
            arn: arn:aws:cognito-idp:us-east-1:321082332978:userpool/us-east-1_mLWq9MaYx

  getFoodImage:
    handler: resources/food.getFoodImage
    events:
      - http:
          path: /food/image/{key}
          method: get
          authorizer:
            arn: arn:aws:cognito-idp:us-east-1:321082332978:userpool/us-east-1_mLWq9MaYx

  placeOrder:
    handler: resources/orders.placeOrder
    vpc: ${self:custom.vpc}
    events:
      - http:
          path: /orders
          method: post
          authorizer:
            arn: arn:aws:cognito-idp:us-east-1:321082332978:userpool/us-east-1_mLWq9MaYx
  
  cancelOrder:
    handler: resources/orders.cancelOrder
    vpc: ${self:custom.vpc}
    events:
      - http:
          path: /orders
          method: delete
          authorizer:
            arn: arn:aws:cognito-idp:us-east-1:321082332978:userpool/us-east-1_mLWq9MaYx
