service: aws-postgres-server

frameworkVersion: '2'


provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'
  vpc:
    securityGroupIds:
      - sg-36cc262a
    subnetIds:
      - subnet-c30953e2
      - subnet-788fd31e
      - subnet-b2fc9c83
      - subnet-f66d81ba
      - subnet-ac92cbf3
      - subnet-9ac8de94

plugins:
  - serverless-offline

functions:
  getUserOrders:
    handler: resources/users.getUserOrders
    events:
      - http:
          path: /users/orders/{username}/{page}
          method: get
          authorizer:
            arn: arn:aws:cognito-idp:us-east-1:321082332978:userpool/us-east-1_mLWq9MaYx

  placeOrder:
    handler: resources/orders.placeOrder
    events:
      - http:
          path: /orders
          method: post
          authorizer:
            arn: arn:aws:cognito-idp:us-east-1:321082332978:userpool/us-east-1_mLWq9MaYx
  
  cancelOrder:
    handler: resources/orders.cancelOrder
    events:
      - http:
          path: /orders
          method: delete
          authorizer:
            arn: arn:aws:cognito-idp:us-east-1:321082332978:userpool/us-east-1_mLWq9MaYx
